<Mouse>:

<Keyboard>:

<Menu>:
    cols: 2
    rows: 1
    size: app.window_size

    BoxLayout:
        id: controler

    BoxLayout:
        orientation: 'vertical'
        size_hint_x: .08

        Button:
            text: 'Mouse'
            font_size: 15
            on_press: root.select_controler(1)
        Button:
            text: 'Keyboard'
            font_size: 15
            on_press: root.select_controler(2)